on: push
# on:
#   schedule:
#     - cron:  '01 0 * * 1'

jobs:
    delete-old-releases:
        name: Delete old releases
        runs-on: ubuntu-latest
        steps:
            - uses: sgpublic/delete-release-action@v1.2
              env:
                GITHUB_TOKEN: ${{ secrets.TOKEN }}
              with:
                release-drop: true
                release-keep-count: 2
                release-drop-tag: true
                pre-release-drop: true
                pre-release-keep-count: 2
                pre-release-drop-tag: true
