name: Cleanup old releases

# on: push
on:
  schedule:
    - cron:  '21 21 * * *'

jobs:
    delete-old-releases:
        name: Delete old releases
        runs-on: ubuntu-latest
        steps:
            - uses: sgpublic/delete-release-action@master
              with:
                release-drop: true
                release-keep-count: 1
                release-drop-tag: true
                pre-release-drop: true
                pre-release-keep-count: 1
                pre-release-drop-tag: true
              env:
                GITHUB_TOKEN: ${{ github.token }}
