# on: push
on:
  schedule:
    - cron:  '01 0 */3 * *'

jobs:
    delete-old-releases:
        name: Delete old releases
        runs-on: ubuntu-latest
        steps:
            - uses: sgpublic/delete-release-action@v1.2
              with:
                release-drop: true
                release-keep-count: 2
                release-drop-tag: true
                pre-release-drop: true
                pre-release-keep-count: 2
                pre-release-drop-tag: true
              env:
                GITHUB_TOKEN: ${{ github.token }}
