on: push
# on:
#   schedule:
#     - cron:  '01 0 * * 1'

jobs:
    delete-old-releases:
        name: Delete old releases
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@main
          - uses: Nats-ji/delete-old-releases@v1.0.1
            with:
              token: ${{ secrets.GITHUB_TOKEN }}
              keep-count: 4
              keep-old-minor-releases: false
              include-prerelease: true
