name: WR3000E

on:
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: wr3000e-${{ github.ref }}
  cancel-in-progress: true

env:
  OPENWRT_VERSION: "25.12.2"
  PROFILE: "cudy_wr3000e-v1"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential file libncurses-dev zlib1g-dev gawk git \
            gettext libssl-dev xsltproc rsync wget unzip python3 zstd
          sudo apt-get clean

      - name: Download Image Builder
        run: |
          wget -q "https://downloads.openwrt.org/releases/${OPENWRT_VERSION}/targets/mediatek/filogic/openwrt-imagebuilder-${OPENWRT_VERSION}-mediatek-filogic.Linux-x86_64.tar.zst"
          tar --zstd -xf openwrt-imagebuilder-*.tar.zst
          mv openwrt-imagebuilder-*/ imagebuilder/

      - name: Build image
        run: |
          cd imagebuilder
          make image \
            PROFILE="${PROFILE}" \
            PACKAGES=" \
              luci \
            "

      - name: TAR output
        run: tar -cvf wr3000e-images.tar imagebuilder/bin/targets/mediatek/filogic

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wr3000e-images
          path: wr3000e-images.tar
          if-no-files-found: error
          retention-days: 14

  release:
    name: Make a release
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: wr3000e-images

      - name: Extract artifacts
        run: tar xf wr3000e-images.tar

      - name: Get the current date
        run: echo "NOW=$(date +%F)" >> "$GITHUB_ENV"

      - name: Create a release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "wr3000e-${{ env.NOW }}"
          name: "WR3000E v${{ env.OPENWRT_VERSION }}"
          prerelease: false
          generate_release_notes: false
          files: imagebuilder/bin/targets/mediatek/filogic/*
